<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>EquipmentSimulator.Desktop</RootNamespace>
    <AssemblyName>EquipmentSimulator.Desktop</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EquipmentSimulator.Core\EquipmentSimulator.Core.csproj" />
  </ItemGroup>

</Project>